#!/bin/bash

# Reuse the task-1 result of the currently running
# yolov8x_COCO_40+40_pseudo_label+nsgp+repre experiment for the other IOD
# methods, then launch each method's task-2 training sequentially.
#
# Method-specific task-1 caches (importance.pth / pca_cache.pkl /
# repre_prototypes.pt) are NOT reused across methods: they are generated with
# method-dependent settings (e.g. nsgp uses --scope normalization and
# --uncentered PCA), so they are removed after copying and regenerated by the
# model adapter with each method's own settings before task-2 starts.

set -euo pipefail

OUTPUT_PREFIX="runs/yolov8x_COCO_40+40"
SOURCE_METHOD="pseudo_label+nsgp+repre"
SOURCE_TASK1_DIR="${OUTPUT_PREFIX}_${SOURCE_METHOD}/task-1"
TRAIN_SCRIPT_DIR="scripts/coco/40_40/yolov8"

TARGET_METHODS=(
    "pseudo_label+nsgp"
    "bpf"
    "pseudo_label+dist+espreg"
    "pseudo_label+ewc"
)

# Method-specific caches that must be regenerated per method.
METHOD_ARTIFACTS=(
    "importance.pth"
    "pca_cache.pkl"
    "repre_prototypes.pt"
)

if [[ ! -f "${SOURCE_TASK1_DIR}/best.pt" ]]; then
    echo "Source task-1 model not found: ${SOURCE_TASK1_DIR}/best.pt" >&2
    echo "Wait for the ${SOURCE_METHOD} task-1 training to finish first." >&2
    exit 1
fi

for method in "${TARGET_METHODS[@]}"; do
    target_task1_dir="${OUTPUT_PREFIX}_${method}/task-1"
    mkdir -p "$target_task1_dir"
    cp -r "${SOURCE_TASK1_DIR}/." "$target_task1_dir/"
    for artifact in "${METHOD_ARTIFACTS[@]}"; do
        rm -f "${target_task1_dir}/${artifact}"
    done
    echo "Copied task-1 -> ${target_task1_dir} (method caches cleared)"
done

for method in "${TARGET_METHODS[@]}"; do
    echo "Starting task-2 training: ${method}"
    START_TASK=2 bash "${TRAIN_SCRIPT_DIR}/train_${method}.sh"
done
