# model settings
base_model: runs/yolov8l_voc_inc_15_5_fromscratch/task-1/best.pt
model_cfg: yolov8l.yaml
# data settings
data_cfg: data/VOC_inc_15_5/task_2_cls_5/dataconfig.yaml
base_data_cfg: data/VOC_inc_15_5/task_1_cls_15/dataconfig.yaml
# training settings
epochs: 100
batch: 16
workers: 8
device: 0
frozen_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8]
# projection settings
pca_sample_num: 100
projection_layers: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]