# model settings
base_model: runs/yolov8l_voc_inc_15_5_fromscratch/task-1/best.pt
model_cfg: yolov8l.yaml
# data settings
data_cfg: data/VOC_inc_15_5/task_2_cls_5/dataconfig.yaml
base_data_cfg: data/VOC_inc_15_5/task_1_cls_15/dataconfig.yaml
# training settings
epochs: 100
batch: 16
workers: 8
device: 0
frozen_layers:
# projection settings
pca_sample_num: 500
projection_layers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
pca_cache_save_path: runs/yolov8l_voc_inc_15_5_fromscratch/task-1/pca_cache.joblib
pca_cache_load_path: runs/yolov8l_voc_inc_15_5_fromscratch/task-1/pca_cache.joblib