base_model: runs/yolov8l_voc_inc_15_5_fromscratch/task-1/best.pt
model_cfg: yolov8l.yaml

new_classes:
  - pottedplant
  - sheep
  - sofa
  - train
  - tvmonitor

data_cfg: data/VOC_inc_15_5/task_2_cls_5/dataconfig.yaml
memory_bank_dir: runs/yolov8l_voc_inc_15_5_fromscratch/task-2/osr_memory_bank
num_mixup: 100

epochs: 100
batch: 16
workers: 8
device: 0