base_model: runs/yolov8l_voc_inc_15_5_fromscratch_naive/task-1/best.pt
model_cfg: yolov8l.yaml

new_classes:
  - pottedplant
  - sheep
  - sofa
  - train
  - tvmonitor

data_cfg: /hy-tmp/datasets/VOC_inc_15_5/task_2_cls_5/dataconfig.yaml

epochs: 100
batch: 16
workers: 8
device: 0