# model settings
base_model: runs/yolov8l_voc_inc_15_1x5_fromscratch/task-4/best.pt
model_cfg: yolov8l.yaml
# data settings
data_cfg: data/VOC_inc_15_1x5/task_5_cls_1/dataset.yaml
# training settings
epochs: 100
batch: 16
workers: 8
device: 0
frozen_layers: [1, 2, 3, 4, 5, 6, 7, 8, 9]
# projection settings
pca_sample_num: 100
projection_layers:
pca_sample_images: [
  data/VOC_inc_15_1x5/task_1_cls_15/images/train,
  data/VOC_inc_15_1x5/task_2_cls_1/images/train,
  data/VOC_inc_15_1x5/task_3_cls_1/images/train,
  data/VOC_inc_15_1x5/task_4_cls_1/images/train]
pca_sample_labels: [
  data/VOC_inc_15_1x5/task_1_cls_15/labels/train,
  data/VOC_inc_15_1x5/task_2_cls_1/labels/train,
  data/VOC_inc_15_1x5/task_3_cls_1/labels/train,
  data/VOC_inc_15_1x5/task_4_cls_1/labels/train]
pca_cache_save_path: runs/yolov8l_voc_inc_15_1x5_fromscratch/task-4/pca_cache.joblib
pca_cache_load_path:
