python tools/train.py \
    --model /root/myultralytics/runs/yolov8l_4-domain_pretrained-yoloe_pseudo_label+proto_rp/task-1/best.pt \
    --data /root/myultralytics/data/4-domain/voc/dataset.yaml \
    --epochs 100 \
    --batch_size 16 \
    --imgsz 640 \
    --trainer antiforget \
    --freeze "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]" \
    --proto_rp True \
    --prototypes /root/myultralytics/runs/yolov8l_4-domain_pretrained-yoloe_pseudo_label+proto_rp/task-1/prototypes.pt \
    --proto_rp_use_base_model False \
    --proto_rp_loss_weight 0.5